databases:
  - name: mozumin_DB
    databaseName: mozumin_db
    user: mozumin_db_user
    region: singapore

services:
  - type: web
    name: mozumin
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mozumin_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

